# Generated by Django 5.2.10 on 2026-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="parsed_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="raw_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
