# Generated by Django 5.2.10 on 2026-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_hrprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("HR", "HR"), ("JOB_SEEKER", "Job Seeker")],
                max_length=20,
                null=True,
            ),
        ),
    ]
